name: Terraform Helm Module

on:
  push:
    branches: [ main, feature/* ]    
  pull_request:
    branches: [ feature/* ]
    
  workflow_dispatch: 

jobs:
  terraform:
    uses: the-bob/github-workflows/.github/workflows/terraform.yml@main
    with:
       name: "Terraform Helm"
    secrets:  
       github_token: ${{ secrets.GITHUB_TOKEN }}
